# Generated by Django 5.1.5 on 2025-02-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='status',
        ),
    ]
