# Generated by Django 5.1.5 on 2025-02-13 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmessage',
            options={'ordering': ['date_sent'], 'verbose_name': 'Личное_сообщения', 'verbose_name_plural': 'Личные_сообщения'},
        ),
        migrations.RenameField(
            model_name='directmessage',
            old_name='time_sent',
            new_name='date_sent',
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='body',
            field=models.CharField(max_length=324),
        ),
    ]
