# Generated by Django 5.1.5 on 2025-01-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatAPI', '0002_chatgroup_groupmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatgroup',
            options={'verbose_name': 'Название чата', 'verbose_name_plural': 'Названия чатов'},
        ),
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='body',
            field=models.CharField(max_length=324, verbose_name='Сообщение'),
        ),
    ]
