# Generated by Django 5.1.5 on 2025-03-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatAPI', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
