# Generated by Django 5.1.5 on 2025-01-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatAPI', '0003_alter_chatgroup_options_alter_groupmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['-date_sent'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='group_slug',
            field=models.SlugField(default=4, max_length=128, unique=True, verbose_name='Слаг'),
        ),
    ]
