# Generated by Django 5.1.5 on 2025-02-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatAPI', '0004_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo')),
            ],
        ),
        migrations.AlterModelOptions(
            name='directmessage',
            options={'verbose_name': 'Личное_сообщения', 'verbose_name_plural': 'Личные_сообщения'},
        ),
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'verbose_name': 'Группа_сообщения', 'verbose_name_plural': 'Группы_сообщения'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
