# Generated by Django 5.1.5 on 2025-01-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatAPI', '0004_alter_groupmessage_options_chatgroup_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Слаг'),
        ),
    ]
