# Generated by Django 5.1.5 on 2025-01-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatAPI', '0007_directmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmessage',
            options={'ordering': ['-time_sent'], 'verbose_name': 'Личное_сообщения', 'verbose_name_plural': 'Личные_сообщения'},
        ),
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['-date_sent'], 'verbose_name': 'Группа_сообщения', 'verbose_name_plural': 'Группы_сообщения'},
        ),
    ]
