# Generated by Django 5.1.5 on 2025-01-28 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatAPI', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='group_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователи чата'),
        ),
    ]
