# Generated by Django 5.1.5 on 2025-02-01 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatAPI', '0010_chatgroup_group_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['date_sent'], 'verbose_name': 'Группа_сообщения', 'verbose_name_plural': 'Группы_сообщения'},
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='group_admin_users',
            field=models.ManyToManyField(related_name='group_admins', to=settings.AUTH_USER_MODEL, verbose_name='Админы'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_users',
            field=models.ManyToManyField(related_name='group_users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи чата'),
        ),
    ]
