# Generated by Django 5.1.5 on 2025-02-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatAPI', '0012_chatgroup_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatgroup',
            options={'verbose_name': 'Групповой чат', 'verbose_name_plural': 'Групповые чаты'},
        ),
    ]
