# Generated by Django 5.1.5 on 2025-02-05 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatAPI', '0014_alter_chatgroup_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
