# Generated by Django 5.1.5 on 2025-02-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatAPI', '0015_user_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Friends',
            new_name='friends',
        ),
    ]
